package it.objectmethod.tatami.utils;

public class QueryConstants {

	public static final String[] LOBBY_SEARCH = {
		"WITH lobbies AS (( \n"
			+ "  SELECT l.*, 1 AS friends FROM lobby l \n"
			+ "    JOIN user u1 ON u1.id = lobby.user_1_id \n"
			+ "    JOIN user_user r1 ON u1.id = r1.user_2_id \n"
			+ "      AND r1.relationship = 'FRIEND' \n"
			+ "      AND r1.user_1_id = ? \n"
			+ ") UNION ALL ( \n"
			+ "  SELECT l.*, 1 AS friends FROM lobby l \n"
			+ "    JOIN user u2 ON u2.id = lobby.user_2_id \n"
			+ "    JOIN user_user r2 ON u2.id = r2.user_2_id \n"
			+ "      AND r2.relationship = 'FRIEND' \n"
			+ "      AND r2.user_1_id = ? \n"
			+ ") UNION ALL ( \n"
			+ "  SELECT l.*, 1 AS friends FROM lobby l \n"
			+ "    JOIN user u3 ON u3.id = lobby.user_3_id \n"
			+ "    JOIN user_user r3 ON u3.id = r3.user_2_id \n"
			+ "      AND r3.relationship = 'FRIEND' \n"
			+ "      AND r3.user_1_id = ? \n"
			+ ") UNION ALL ( \n"
			+ "  SELECT l.*, 1 AS friends FROM lobby l \n"
			+ "    JOIN user u4 ON u4.id = lobby.user_4_id \n"
			+ "    JOIN user_user r4 ON u4.id = r4.user_2_id \n"
			+ "      AND r4.relationship = 'FRIEND' \n"
			+ "      AND r4.user_1_id = ? \n"
			+ ") UNION ALL ( \n"
			+ "  SELECT l.*, 0 AS friends FROM lobby l \n"
			+ "  WHERE l.lobby_type = 'PUBLIC' \n"
			+ ")) \n"
			+ "SELECT lob.id AS id \n"
			+ ", lob.user_1_id AS user_1_id \n"
			+ ", lob.user_2_id AS user_2_id \n"
			+ ", lob.user_3_id AS user_3_id \n"
			+ ", lob.user_4_id AS user_4_id \n"
			+ ", lob.last_in_lobby_1 AS last_in_lobby_1 \n"
			+ ", lob.last_in_lobby_2 AS last_in_lobby_2 \n"
			+ ", lob.last_in_lobby_3 AS last_in_lobby_3 \n"
			+ ", lob.last_in_lobby_4 AS last_in_lobby_4 \n"
			+ ", lob.lobby_type AS lobby_type \n"
			+ ", lob.lobby_name AS lobby_name \n"
			+ ", lob.game_id AS game_id \n"
			+ ", SUM(lob.friends)  AS sum_friends"
			+ " FROM lobbies lob \n"
			+ "WHERE (lob.user_1_id IS NULL OR lob.user_2_id IS NULL OR lob.user_3_id IS NULL OR lob.user_4_id IS NULL) \n",
		"GROUP BY lob.id \n"
			+ ", lob.user_1_id \n"
			+ ", lob.user_2_id \n"
			+ ", lob.user_3_id \n"
			+ ", lob.user_4_id \n"
			+ ", lob.last_in_lobby_1 \n"
			+ ", lob.last_in_lobby_2 \n"
			+ ", lob.last_in_lobby_3 \n"
			+ ", lob.last_in_lobby_4 \n"
			+ ", lob.lobby_type \n"
			+ ", lob.lobby_name \n"
			+ ", lob.game_id \n"
			+ "ORDER BY SUM(lob.friends) DESC, id ASC \n"
			+ "LIMIT ? , ?" };
}
