package it.objectmethod.tatami.entity.enums;

public enum LogAction {

	END_TURN, SKIP_TURN, BEGIN_TURN, BEGIN_UNLOCK, UNLOCK, END_UNLOCK, BEGIN_EARN, EARN, EMERGENCY_EARN, END_EARN, BEGIN_MOVEMENT, GAIN_MOVE_ACTIONS, GAIN_STEPS, MOVE, ROTATE, TRANSLATE, PAY, PAY_TRANSIT, BEGIN_BATTLE, CHECK_ADVANTAGE, ROLL_BATTLE, CHECK_WINNER, LOCK, GAIN_TATAMI, LOOSE_TATAMI, END_MOVEMENT, ACCESS_SHOP, DRAW, BUY_GREEN, USE_ACTION, DISCARD_GREEN, END_SHOP, LOOSE_GAME, WIN_GAME, TELEPORT, FULL_UNLOCK, DIG, STEAL_GREEN, STEAL_TATAMI, EARNING_GREEN, USE_EARNING_GREEN, REROLL_YOUR_TURN, REROLL_ONE, DIG_PLUS;
}
